# ===============================
# APPLICATION NAME
# ===============================
spring.application.name=greenfield_schooGreenFieldSchool

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
server.port=${SERVER_PORT}

spring.security.user.name=${SPRING_SECURITY_USER_NAME}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD}
spring.security.user.roles=${SPRING_SECURITY_USER_ROLES}
# ===============================
# WEATHER API
# ===============================
weather.api.key=abcd1234efgh5678ijkl9012mnop3456